import { Geist, Geist_Mono,Murecho  } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const murecho = Murecho({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Specify needed weights
});

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className="text-[3.29vw] sm:text-[2.5vw] md:text-[2.08vw] lg:text-[1.35vw]">
      <body
        className={`${geistSans.variable} ${geistMono.variable}${murecho.className} antialiased relative`}
      >

          {/* navbar */}

        <header>
         <Navbar></Navbar>
        </header>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
